# Generated by Django 6.0.1 on 2026-09-02 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_department_course_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='academicyear',
            options={'ordering': ['-start_date']},
        ),
        migrations.AlterModelOptions(
            name='classroom',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['code']},
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['code']},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['code']},
        ),
    ]
