# Generated by Django 6.0.1 on 2026-09-02 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_student_parent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['admission_no']},
        ),
    ]
