# Generated by Django 6.0.1 on 2026-09-03 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_alter_academicyear_options_alter_classroom_options_and_more'),
        ('teachers', '0002_alter_teacher_options'),
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='timetableentry',
            name='unique_slot_per_class',
        ),
        migrations.AddConstraint(
            model_name='timetableentry',
            constraint=models.UniqueConstraint(condition=models.Q(('section__isnull', False)), fields=('classroom', 'section', 'weekday', 'period'), name='unique_slot_per_class_section'),
        ),
        migrations.AddConstraint(
            model_name='timetableentry',
            constraint=models.UniqueConstraint(condition=models.Q(('section__isnull', True)), fields=('classroom', 'weekday', 'period'), name='unique_slot_per_class'),
        ),
    ]
