# Generated by Django 6.0.1 on 2026-09-03 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_alter_academicyear_options_alter_classroom_options_and_more'),
        ('teachers', '0002_alter_teacher_options'),
        ('timetable', '0002_remove_timetableentry_unique_slot_per_class_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='timetableentry',
            name='unique_slot_per_teacher',
        ),
        migrations.RemoveConstraint(
            model_name='timetableentry',
            name='unique_slot_per_room',
        ),
        migrations.RemoveConstraint(
            model_name='timetableentry',
            name='unique_slot_per_class_section',
        ),
        migrations.RemoveConstraint(
            model_name='timetableentry',
            name='unique_slot_per_class',
        ),
        migrations.AddField(
            model_name='timetableentry',
            name='section_key',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddConstraint(
            model_name='timetableentry',
            constraint=models.UniqueConstraint(fields=('classroom', 'section_key', 'weekday', 'period'), name='unique_slot_per_class'),
        ),
        migrations.AddConstraint(
            model_name='timetableentry',
            constraint=models.UniqueConstraint(fields=('teacher', 'weekday', 'period'), name='unique_slot_per_teacher'),
        ),
        migrations.AddConstraint(
            model_name='timetableentry',
            constraint=models.UniqueConstraint(fields=('room', 'weekday', 'period'), name='unique_slot_per_room'),
        ),
    ]
