# Generated by Django 6.0.1 on 2026-09-02 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bus',
            options={'ordering': ['registration_number'], 'verbose_name_plural': 'buses'},
        ),
        migrations.AlterModelOptions(
            name='driver',
            options={'ordering': ['license_number']},
        ),
        migrations.AlterModelOptions(
            name='route',
            options={'ordering': ['code']},
        ),
        migrations.AlterModelOptions(
            name='studenttransport',
            options={'ordering': ['student__admission_no']},
        ),
    ]
