"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

import os
import sys
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / ".env")

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY =os.getenv("SECRET_KEY")
#'django-insecure-8_7e=_skky$)7fk_0j!m(z51r$m7i@c$uuzwts_v721emloy8-'

# SECURITY WARNING: don't run with debug turned on in production!

DEBUG = os.getenv("DEBUG") == "True"


# Comma-separated in the environment, e.g. "localhost,127.0.0.1,school.example.com".
# Empty while DEBUG is on so the dev server still answers on localhost.
ALLOWED_HOSTS = [
    host.strip()
    for host in os.getenv("ALLOWED_HOSTS", "").split(",")
    if host.strip()
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    'apps.accounts',
    'apps.students',
    'apps.organizations',
    "apps.teachers",
    "apps.academics",
    "apps.parents",
    "apps.common",
    "apps.transport",
    "apps.attendance",
    "apps.fees",
    "apps.examinations",
    "apps.notifications",
    "apps.dashboard",
    "apps.web",
    'rest_framework',
    # Needed by ROTATE_REFRESH_TOKENS: a rotated-away refresh token must stop
    # working, which means remembering that it was rotated.
    "rest_framework_simplejwt.token_blacklist",
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": {
        # Defaults to SQLite so a fresh checkout runs with no database server.
        # Docker Compose supplies the MySQL values through the environment.
        "ENGINE": os.getenv("DB_ENGINE", "django.db.backends.sqlite3"),
        "NAME": os.getenv("DB_NAME", str(BASE_DIR / "db.sqlite3")),
        "USER": os.getenv("DB_USER", ""),
        "PASSWORD": os.getenv("DB_PASSWORD", ""),
        "HOST": os.getenv("DB_HOST", ""),
        "PORT": os.getenv("DB_PORT", ""),
    }
}




#DATABASES = {
 #   'default': {
  #      'ENGINE': 'django.db.backends.mysql',
   #     'NAME': 'student_management_db',
    #    'USER': 'root',
     #   'PASSWORD': 'password',
      #  'HOST': 'localhost',
       # 'PORT': '3306',
    #}
#}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"
# Where collectstatic writes for the Nginx/Gunicorn deployment in Phase 6.
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_DIRS = [BASE_DIR / "static"] if (BASE_DIR / "static").exists() else []

# Uploaded profile photos and organization logos.
MEDIA_URL = "media/"
MEDIA_ROOT = BASE_DIR / "media"
# Custom User Model
AUTH_USER_MODEL = "accounts.User"

# Django REST Framework Configuration
REST_FRAMEWORK = {
    # Cookie first, Authorization header second. Browsers get httpOnly cookies
    # that XSS cannot read; API and mobile clients keep using the header.
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "apps.accounts.authentication.CookieJWTAuthentication",
    ),
    # Fail closed: every endpoint requires authentication unless it
    # explicitly sets permission_classes (register/login use AllowAny).
    "DEFAULT_PERMISSION_CLASSES": (
        "rest_framework.permissions.IsAuthenticated",
    ),
    # A college with three thousand students would otherwise serialise every
    # one of them on each list request. Views that return a fixed-size summary
    # opt out with pagination_class = None.
    "DEFAULT_PAGINATION_CLASS": "apps.common.pagination.StandardPagination",
    "PAGE_SIZE": 25,
    # Sign-in is the one endpoint an attacker can hammer without an account, so
    # it gets its own much tighter bucket. The rest exist to stop a runaway
    # client, not an attacker.
    "DEFAULT_THROTTLE_CLASSES": (
        "rest_framework.throttling.ScopedRateThrottle",
    ),
    "DEFAULT_THROTTLE_RATES": {
        "login": "10/min",
        "register": "5/hour",
        "scan": "120/min",      # a busy gate at 8am reads a card every second
        "user": "1000/hour",
    },
}

from datetime import timedelta  # noqa: E402 - kept beside the settings it feeds

SIMPLE_JWT = {
    # Short access tokens limit the damage of a leaked one; the refresh token
    # is what keeps a user signed in, and it rotates on every use so a stolen
    # one stops working as soon as the real user refreshes.
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=30),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "UPDATE_LAST_LOGIN": True,
    "AUTH_HEADER_TYPES": ("Bearer",),
}



# Notifications
# The SMS gateway is pluggable; the default backend logs instead of sending so
# development and tests never hit a paid API. Point SMS_BACKEND at a real
# class to go live.
SMS_BACKEND = os.getenv("SMS_BACKEND", "")

# Online payment gateway. Empty uses the console gateway, which settles nothing
# and must never be used in production.
PAYMENT_GATEWAY = os.getenv("PAYMENT_GATEWAY", "")

# Razorpay credentials, when PAYMENT_GATEWAY points at that backend. Read from
# the environment: a key committed to the repository is a key that has to be
# rotated.
RAZORPAY_KEY_ID = os.getenv("RAZORPAY_KEY_ID", "")
RAZORPAY_KEY_SECRET = os.getenv("RAZORPAY_KEY_SECRET", "")
DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL", "noreply@smartsms.local")
EMAIL_BACKEND = os.getenv(
    "EMAIL_BACKEND", "django.core.mail.backends.console.EmailBackend"
)

# Templates for the Bootstrap front end live at the project root.
TEMPLATES[0]["DIRS"] = [BASE_DIR / "templates"]

LOGIN_URL = "/login/"
LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = "/login/"


# Production hardening.
# Applied only when DEBUG is off: forcing HTTPS locally would make the dev
# server unreachable, since runserver speaks plain HTTP.
if not DEBUG:
    SECURE_SSL_REDIRECT = os.getenv("SECURE_SSL_REDIRECT", "True") == "True"
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = int(os.getenv("SECURE_HSTS_SECONDS", "31536000"))  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = "DENY"
    # Nginx terminates TLS and forwards the original scheme.
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")


# Test-only: PBKDF2 runs 1.2 million iterations per hash, which is exactly what
# production wants and exactly what makes a suite creating hundreds of users
# take minutes. Only the hashing is weakened, and only while running tests.
if "test" in sys.argv:
    PASSWORD_HASHERS = ["django.contrib.auth.hashers.MD5PasswordHasher"]
