# Generated by Django 6.0.1 on 2026-09-02 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feepayment',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='feepayment',
            name='bank_reference',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='feepayment',
            name='gateway',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='feepayment',
            name='gateway_order_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='feepayment',
            name='instrument_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feepayment',
            name='instrument_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='feepayment',
            name='upi_vpa',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='feepayment',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Cash'), ('UPI', 'UPI'), ('DEBIT_CARD', 'Debit Card'), ('CREDIT_CARD', 'Credit Card'), ('NET_BANKING', 'Net Banking'), ('NEFT', 'NEFT'), ('RTGS', 'RTGS'), ('IMPS', 'IMPS'), ('WALLET', 'Wallet'), ('CHEQUE', 'Cheque'), ('DEMAND_DRAFT', 'Demand Draft')], default='CASH', max_length=15),
        ),
    ]
