# Generated by Django 6.0.1 on 2026-09-02 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0003_migrate_card_payment_method'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feestructure',
            options={'ordering': ['-created_at']},
        ),
    ]
