# Generated by Django 6.0.1 on 2026-09-02 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attendance', '0001_initial'),
        ('students', '0002_student_parent'),
        ('transport', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='busattendance',
            name='bus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_scans', to='transport.bus'),
        ),
        migrations.AddField(
            model_name='busattendance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bus_attendance', to='students.student'),
        ),
        migrations.AddField(
            model_name='busattendance',
            name='trip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_scans', to='transport.trip'),
        ),
        migrations.AddField(
            model_name='studentqrcode',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='qr_code', to='students.student'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['student', '-date'], name='attendance__student_9cfdf9_idx'),
        ),
        migrations.AddConstraint(
            model_name='attendance',
            constraint=models.UniqueConstraint(fields=('student', 'subject', 'date'), name='unique_attendance_per_student_subject_date'),
        ),
        migrations.AddIndex(
            model_name='busattendance',
            index=models.Index(fields=['student', '-scanned_at'], name='attendance__student_fddbcd_idx'),
        ),
    ]
