# Generated by Django 6.0.1 on 2026-09-02 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_initial'),
        ('students', '0002_student_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampusScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_type', models.CharField(choices=[('IN', 'In'), ('OUT', 'Out')], max_length=3)),
                ('device_id', models.CharField(blank=True, max_length=50, null=True)),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
                ('attendance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_scans', to='attendance.attendance')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campus_scans', to='students.student')),
            ],
            options={
                'ordering': ['-scanned_at'],
                'indexes': [models.Index(fields=['student', '-scanned_at'], name='attendance__student_e7139b_idx')],
            },
        ),
    ]
