# Generated by Django 6.0.1 on 2026-09-02 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_campusscan'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentqrcode',
            options={'ordering': ['student__admission_no']},
        ),
    ]
