# Generated by Django 6.0.1 on 2026-09-03 04:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_alter_academicyear_options_alter_classroom_options_and_more'),
        ('attendance', '0004_alter_studentqrcode_options'),
        ('students', '0004_student_archived_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='attendance',
            name='unique_attendance_per_student_subject_date',
        ),
        migrations.AddField(
            model_name='attendance',
            name='subject_key',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddConstraint(
            model_name='attendance',
            constraint=models.UniqueConstraint(fields=('student', 'subject_key', 'date'), name='unique_attendance_per_student_subject_date'),
        ),
    ]
