# Generated by Django 6.0.1 on 2026-09-03 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_alter_academicyear_options_alter_classroom_options_and_more'),
        ('examinations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='examschedule',
            name='unique_paper_per_exam_subject_classroom',
        ),
        migrations.AddField(
            model_name='examschedule',
            name='classroom_key',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddConstraint(
            model_name='examschedule',
            constraint=models.UniqueConstraint(fields=('exam', 'subject', 'classroom_key'), name='unique_paper_per_exam_subject_classroom'),
        ),
    ]
