# Generated by Django 6.0.6 on 2026-07-15 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_code', models.CharField(max_length=20, unique=True)),
                ('organization_name', models.CharField(max_length=200)),
                ('organization_type', models.CharField(choices=[('School', 'School'), ('College', 'College'), ('Coaching Center', 'Coaching Center'), ('University', 'University'), ('Training Institute', 'Training Institute')], max_length=30)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='organization_logos/')),
                ('primary_color', models.CharField(default='#1976D2', max_length=20)),
                ('secondary_color', models.CharField(default='#FFFFFF', max_length=20)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=10)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('website', models.URLField(blank=True)),
                ('subscription_plan', models.CharField(choices=[('Free', 'Free'), ('Basic', 'Basic'), ('Premium', 'Premium'), ('Enterprise', 'Enterprise')], default='Free', max_length=20)),
                ('subscription_start', models.DateField()),
                ('subscription_end', models.DateField()),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
