# Generated by Django 6.0.1 on 2026-09-02 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='day_start_time',
            field=models.TimeField(default='08:00'),
        ),
        migrations.AddField(
            model_name='organization',
            name='late_after_time',
            field=models.TimeField(default='09:15'),
        ),
    ]
