# Generated by Django 6.0.1 on 2026-09-02 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_organization_day_start_time_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organization',
            options={'ordering': ['organization_name']},
        ),
    ]
